name: flutter_chat_types

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  test: ^1.24.3
